name: Kufar Bot

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

permissions:
  contents: write

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Kufar bot
        run: python kufar_bot.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}

      - name: Save seen ads
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add seen_ads.json

          git commit -m "Update seen ads" || echo "No changes"

          git push
