name: Kufar Bot

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check secrets
        run: |
          if [ -z "$TELEGRAM_TOKEN" ]; then
            echo "TOKEN EMPTY"
          else
            echo "TOKEN EXISTS"
          fi

          if [ -z "$CHAT_ID" ]; then
            echo "CHAT EMPTY"
          else
            echo "CHAT EXISTS"
          fi
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}

      - name: Run Kufar bot
        run: python kufar_bot.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
